### ISSUE TITLE
Suomen rajat aluemeren ulkorajan mukaisesti

### ISSUE THREAD

**Issue by haukkovaara** [teelmo/geodata#1]
Tervehdys Teemo!

Olisiko saatavilla Suomen rajoja KML-formaatissa niin että merialueilla raja seuraa Suomen aluemeren ulkorajaa - ei siis rantaviivaa?

**Comment by teelmo** [comment]
Vastaan myös tänne, että nyt löytyy täältä: https://github.com/teelmo/geodata/blob/master/kml/Suomi%20Aluevesirajoilla.kml
